global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "nginx"
    static_configs:
      - targets: ["talkpick-nginx-exporter:9113"]
  - job_name: 'loki'
    static_configs:
      - targets: [ 'talkpick-loki:3100' ]
  - job_name: "spring-actuator"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "talkpick-batch:8077" ]